config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :any
    alias_action :create, :read, to: :watch_plus
    alias_action :read, to: :watch

    user ||= User.new

    if user.has_role?(:admin)
      can :any, :all
    elsif user.has_role?(:paid)
      can :watch_plus, :all
    else #user.has_role?(:free)
      can :watch, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # rolify :role_cname => 'Premium'
  # rolify :role_cname => 'Free'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  authorize_resource class: false, unless: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    if current_user
      render file: "#{Rails.root}/public/403.html", status: 403, layout: false
    else
      render file: "#{Rails.root}/public/401.html", status: 401, layout: false
    end
  end

end

app/controllers/concerns/premiumable.rb
require 'active_support/concern'

module Premiumable
  extend ActiveSupport::Concern

  def manage_premium
    unless current_user.has_role?(:paid) || current_user.has_role?(:admin)
      range = 0..((@post.premium.size * 0.15).ceil)
      @post.premium = ("#{@post.premium[range]}...")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Premiumable
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    manage_premium
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit %i[title body premium]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCanCan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice" class="center">
      <%= notice %>
    </p>

    <% if current_user %>
      <div class="nav">
        <div class="float-left">
          <%= link_to '< Main', root_path %>
        </div>

        <div class="float-right">
          <%= link_to 'Logout', destroy_user_session_path, class: 'btn', method: :delete %>
        </div>
      </div>
    <% end %>

    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :premium %>
    <%= form.text_area :premium %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="center">
  <div class="post-update">

    <h1>Editing Post</h1>

    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', posts_path %>

    <%= render 'form', post: @post %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="center">
  <div class="posts">
    <h1>Posts</h1>

    <br/>

    <%= link_to 'New Post', new_post_path if can? :new, @post %>

    <br/>

    <table>
      <thead>
      <tr>
        <th>ID</th>
        <th></th>
        <th>Title</th>
        <th></th>
        <th>Body</th>
        <th></th>
        <th colspan="5"></th>
      </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.id %></td>
            <td>|</td>
            <td><%= "#{post.title[0..25]} #{'...' if post.title.size > 25}" %></td>
            <td>|</td>
            <td><%= "#{post.body[0..25]} #{'...' if post.body.size > 25}" %></td>
            <td>|</td>
            <td><%= link_to 'Show', post %></td>
            <td><%= link_to 'Edit', edit_post_path(post) if can? :edit, @post %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, @post %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/posts/new.html.erb
<div class="center">
  <div class="post-new">
    <h1>New Post</h1>

    <%= link_to 'Back', posts_path %>

    <%= render 'form', post: @post %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="center">
  <div class="post-show">

    <%= link_to 'Back', posts_path %>
    <%- if can? :edit, @post %>
      | <%= link_to 'Edit', edit_post_path(@post) %>
    <% end %>

    <p>
      <strong>Title:</strong>
      <%= @post.title %>
    </p>

    <p>
      <strong>Body:</strong>
      <%= @post.body %>
    </p>

    <p>
      <strong>Premium:</strong>
      <%= @post.premium %>
    </p>
  </div>
</div>